### ISSUE TITLE
Does it support add edge?

### ISSUE THREAD

**Issue by xchen0012** [SpectoLogic/SpectoLogic.Azure.CosmosDB.Graph#1]
I figure it out....

**Comment by apollak** [comment]
@xchen0012 Thanks, I close this then :-). Suggestions for improvement in documentation, code or sample are always welcome!

**Comment by apollak** [comment]
I updated the [documentation ](https://github.com/SpectoLogic/SpectoLogic.Azure.CosmosDB.Graph/blob/master/README.md). Hopefully it is easier to figure out now
