### ISSUE TITLE
[Question] SpectoLogic Nuget

### ISSUE THREAD

**Issue by charbull** [SpectoLogic/SpectoLogic.Azure.CosmosDB.Graph#2]
Hello,
Very interesting Idea ! :+1:  
Are you planing to propose it as nugets? 

thank you,
Charbel

**Comment by apollak** [comment]
@charbull Yes that is the plan, i just had no time yet. Probably within the next two weeks. Thnx Andreas

**Comment by apollak** [comment]
@charbull Here you go: **SpectoLogic.Azure.Graph -Version 1.0.0-preview**
