### ISSUE TITLE
Help retrieving vertex and adjacent vertices

### ISSUE THREAD

**Issue by prapicault** [SpectoLogic/SpectoLogic.Azure.CosmosDB.Graph#4]
First of all, thanks for your library, this is really of great help.

So far I have been able to use the library with success to retrieve a vertex. Now I'm trying to retrieve a vertex and its adjacent vertices in one query and I'm confused on how to do that.
So first question, is this supported? If so, is there a special way to construct the gremlin query to enable this?

Here are more details about my example: 
The data model is made of Receipe and Ingredient. A Receipe has a List of Ingredient and the relationship between receipe and ingredient is modeled with an edge. 
When I perform the following query: g.V('receipe334455').outE('ingredient').inV().path() the deserialization never completes.

Thanks in advance for any insight.

**Comment by nmpollak** [comment]
Hi, thanks. Currently you have to read the edges and vertices in a separate query. As far as I can remember I had some issues with the SDK to fetch edges and vertices simultaneously in one query. You have to query first the receipe and it's ingredients and with a second query the edges. The MemoryContext should clue them together after you executed both queries. The sample code and the readme should show that. If you keep struggling you can leave me your email on my website www.spectologic.com and we can try to figure out what's happening.

**Comment by nmpollak** [comment]
Closed due inactivity
